// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: addressbook.proto
// Protobuf Java Version: 4.27.2

package generated_proto_classes;

public interface AddressBookOrBuilder extends
    // @@protoc_insertion_point(interface_extends:proto.AddressBook)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .proto.Person people = 1;</code>
   */
  java.util.List<generated_proto_classes.Person> 
      getPeopleList();
  /**
   * <code>repeated .proto.Person people = 1;</code>
   */
  generated_proto_classes.Person getPeople(int index);
  /**
   * <code>repeated .proto.Person people = 1;</code>
   */
  int getPeopleCount();
  /**
   * <code>repeated .proto.Person people = 1;</code>
   */
  java.util.List<? extends generated_proto_classes.PersonOrBuilder> 
      getPeopleOrBuilderList();
  /**
   * <code>repeated .proto.Person people = 1;</code>
   */
  generated_proto_classes.PersonOrBuilder getPeopleOrBuilder(
      int index);
}
