// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: addressbook.proto
// Protobuf Java Version: 4.27.2

package proto.generated_proto_classes;

public interface AddressBookOrBuilder extends
    // @@protoc_insertion_point(interface_extends:proto.AddressBook)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .proto.Person people = 1;</code>
   */
  java.util.List<Person> 
      getPeopleList();
  /**
   * <code>repeated .proto.Person people = 1;</code>
   */
  Person getPeople(int index);
  /**
   * <code>repeated .proto.Person people = 1;</code>
   */
  int getPeopleCount();
  /**
   * <code>repeated .proto.Person people = 1;</code>
   */
  java.util.List<? extends PersonOrBuilder>
      getPeopleOrBuilderList();
  /**
   * <code>repeated .proto.Person people = 1;</code>
   */
  PersonOrBuilder getPeopleOrBuilder(
      int index);
}
